import { useState } from 'react'
import { Share2, Check, Copy, Link } from 'lucide-react'

export default function ShareButton({ riskProfile, address, aiReport }) {
  const [showMenu, setShowMenu] = useState(false)
  const [copied, setCopied] = useState(false)

  const buildShareText = () => {
    const lines = [`SafeHaven Risk Report for ${address}`, '']
    lines.push(`Overall Risk: ${riskProfile.overall_risk}`)
    lines.push('')

    if (riskProfile.risks) {
      const labels = { hurricane: 'Hurricane', flood: 'Flood', earthquake: 'Earthquake', wildfire: 'Wildfire' }
      for (const [key, label] of Object.entries(labels)) {
        const r = riskProfile.risks[key]
        if (r) {
          lines.push(`${label}: ${r.severity} (${r.score}/100)`)
        }
      }
    }

    lines.push('')
    lines.push('Generated by SafeHaven — AI-Powered Disaster Resilience')
    lines.push('https://safehaven.app')

    return lines.join('\n')
  }

  const handleCopyText = async () => {
    try {
      await navigator.clipboard.writeText(buildShareText())
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback
      const textarea = document.createElement('textarea')
      textarea.value = buildShareText()
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
    setShowMenu(false)
  }

  const handleCopyLink = async () => {
    const params = new URLSearchParams({ address })
    const url = `${window.location.origin}/dashboard?${params.toString()}`
    try {
      await navigator.clipboard.writeText(url)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {}
    setShowMenu(false)
  }

  const handleNativeShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `SafeHaven Risk Report — ${address}`,
          text: buildShareText(),
        })
      } catch {}
    }
    setShowMenu(false)
  }

  return (
    <div className="relative">
      <button
        onClick={() => {
          if (navigator.share) {
            handleNativeShare()
          } else {
            setShowMenu(!showMenu)
          }
        }}
        className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-bg-secondary border border-white/10 hover:border-white/20 text-text-primary text-xs font-medium transition-colors"
      >
        {copied ? (
          <>
            <Check className="w-3.5 h-3.5 text-green-400" />
            <span className="text-green-400">Copied!</span>
          </>
        ) : (
          <>
            <Share2 className="w-3.5 h-3.5" />
            <span>Share</span>
          </>
        )}
      </button>

      {showMenu && !copied && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setShowMenu(false)} />
          <div className="absolute bottom-full left-0 mb-1 bg-bg-secondary border border-white/10 rounded-lg shadow-2xl overflow-hidden z-50 w-48">
            <button
              onClick={handleCopyText}
              className="w-full px-3 py-2.5 flex items-center gap-2 text-left text-xs text-text-primary hover:bg-white/5 transition-colors"
            >
              <Copy className="w-3.5 h-3.5 text-text-secondary" />
              Copy report as text
            </button>
            <button
              onClick={handleCopyLink}
              className="w-full px-3 py-2.5 flex items-center gap-2 text-left text-xs text-text-primary hover:bg-white/5 transition-colors border-t border-white/5"
            >
              <Link className="w-3.5 h-3.5 text-text-secondary" />
              Copy link
            </button>
          </div>
        </>
      )}
    </div>
  )
}
